name: personal_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  http: ^1.2.1

  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  # To add assets like images, you would add them here.
  # assets:
  #   - images/a_dot_burr.jpeg

  # This is the configuration for the flutter_launcher_icons package.
  # It must be at the same indentation level as the 'flutter:' key above.
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21 # Set this to your app's minimum Android SDK version.