name: personal_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# This is the ONLY dependencies section you need.
dependencies:
  flutter:
    sdk: flutter

  # Standard iOS icons package.
  cupertino_icons: ^1.0.8

  # This is the http package we added for internet access.
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# This section is for Flutter-specific configurations.
flutter:

  # This line enables the standard Material Design icons.
  uses-material-design: true

  # To add assets like images, you would add them here.
  # assets:
  #   - images/a_dot_burr.jpeg